/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import static Database.ConnectCassandra.createSession;
import Database.Service.Customer_ProductService;
import Model.Customer;
import com.datastax.oss.driver.api.core.CqlSession;
import  Model.Customer_Product;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class pnlCustomer_Product extends javax.swing.JPanel {

    
    private DefaultTableModel tableModel;
    private Customer_ProductService customer_ProductService;
    CqlSession cqlSession = createSession();
    
    public pnlCustomer_Product() {
        initComponents();
         customer_ProductService = new Customer_ProductService(cqlSession);
        loadAllCustomers();
        
    }
    private void loadAllCustomers() {
        List<Customer_Product> products = customer_ProductService.getAll();
        String[] columnNames = {"Customer ID", "Product ID"};
        tableModel = new DefaultTableModel(columnNames, 0);
        tblCustomer_Products.setModel(tableModel);
        tableModel.setRowCount(0); 
        for (Customer_Product customer : products) {
            Object[] rowData = {
                customer.customer_id,
                customer.product_id,
            };
            tableModel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer_Products = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCustomerID = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtProductID = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAddCustomerPR = new javax.swing.JButton();
        btnDeleteCustomerPr = new javax.swing.JButton();
        btnUpadteCustomerPr = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        tblCustomer_Products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustomer_Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomer_ProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer_Products);

        txtCustomerID.setEnabled(false);
        jScrollPane3.setViewportView(txtCustomerID);

        txtProductID.setEnabled(false);
        jScrollPane5.setViewportView(txtProductID);

        jLabel1.setText("Mã khách hàng ");

        jLabel3.setText("Mã sản phẩm");

        btnAddCustomerPR.setText("Thêm khách hàng ");
        btnAddCustomerPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerPRActionPerformed(evt);
            }
        });

        btnDeleteCustomerPr.setText("Xóa khách hàng");
        btnDeleteCustomerPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerPrActionPerformed(evt);
            }
        });

        btnUpadteCustomerPr.setText("Cập nhật ");
        btnUpadteCustomerPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpadteCustomerPrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddCustomerPR)
                                .addGap(141, 141, 141)
                                .addComponent(btnDeleteCustomerPr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpadteCustomerPr)))))
                .addGap(0, 126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpadteCustomerPr)
                    .addComponent(btnDeleteCustomerPr)
                    .addComponent(btnAddCustomerPR))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerPRActionPerformed
         // TODO add your handling code here:
        String customerID = txtCustomerID.getText();
        String productID = txtProductID.getText();
        Customer_Product customer_Product = new Customer_Product(customerID, productID);
        customer_ProductService.addCustomer_Product(customer_Product);
        loadAllCustomers();
    }//GEN-LAST:event_btnAddCustomerPRActionPerformed

    private void btnDeleteCustomerPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerPrActionPerformed
       int selectedRow = tblCustomer_Products.getSelectedRow();
    if (selectedRow != -1) {
        // Lấy ID của khách hàng từ hàng đã chọn
        String customerID = tblCustomer_Products.getValueAt(selectedRow, 0).toString();
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa khách hàng này không ?", "Xác nhận xóa khách hàng", javax.swing.JOptionPane.YES_NO_OPTION);
        // Xóa khách hàng
        
        if(confirm == javax.swing.JOptionPane.YES_OPTION)
        {   
        customer_ProductService.deleteCustomer_Product(customerID);
        // Tải lại danh sách khách hàng
        loadAllCustomers();
        }
    } else {
        // Hiển thị thông báo nếu không có hàng nào được chọn
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một khách hàng để xóa.");
    }
    }//GEN-LAST:event_btnDeleteCustomerPrActionPerformed

    private void btnUpadteCustomerPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpadteCustomerPrActionPerformed
          // Kiểm tra xem người dùng đã chọn hàng nào trong bảng chưa
    int selectedRow = tblCustomer_Products.getSelectedRow();
    if (selectedRow != -1) { // Nếu có hàng được chọn
        // Lấy thông tin khách hàng từ hàng đã chọn
        String customerID = tblCustomer_Products.getValueAt(selectedRow, 0).toString();
        String productID = txtProductID.getText();
        
        // Tạo đối tượng Customer mới với thông tin đã chỉnh sửa
        Customer_Product customer_Product = new Customer_Product(customerID, productID);
        
        // Gọi phương thức cập nhật khách hàng từ CustomerService
        customer_ProductService.updateCustomer_Product(customer_Product);
        
        // Tải lại danh sách khách hàng
        loadAllCustomers();
    } else {
        // Nếu không có hàng nào được chọn, hiển thị thông báo
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Vui lòng chọn một khách hàng để sửa.");
    }
    }//GEN-LAST:event_btnUpadteCustomerPrActionPerformed

    private void tblCustomer_ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomer_ProductsMouseClicked
        int selectedRow = tblCustomer_Products.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy thông tin khách hàng đã chọn
            txtCustomerID.setText(tblCustomer_Products.getValueAt(selectedRow, 0).toString());
            txtProductID.setText(tblCustomer_Products.getValueAt(selectedRow, 1).toString());
        }   
    }//GEN-LAST:event_tblCustomer_ProductsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomerPR;
    private javax.swing.JButton btnDeleteCustomerPr;
    private javax.swing.JButton btnUpadteCustomerPr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTable tblCustomer_Products;
    private javax.swing.JTextPane txtCustomerID;
    private javax.swing.JTextPane txtProductID;
    // End of variables declaration//GEN-END:variables
}
