/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import static Database.ConnectCassandra.createSession;
import Database.Service.CustomerService;
import Model.Customer;
import com.datastax.oss.driver.api.core.CqlSession;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import com.google.gson.Gson; // Thư viện Gson để chuyển đổi đối tượng thành JSON
import javax.swing.JOptionPane; // Để hiển thị thông báo cho người dùng
import java.io.FileWriter; // Để ghi dữ liệu vào file
import java.io.IOException; // Để xử lý ngoại lệ liên quan đến I/O

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.BufferedWriter;
import java.io.File;

/**
 *
 * @author LENOVO
 */
public class pnlCustomer extends javax.swing.JPanel {

    /**
     * Creates new form pnlCustomer
     */
    private DefaultTableModel tableModel;
    private CustomerService customerService;
    CqlSession cqlSession = createSession();

    public pnlCustomer() {
        initComponents();
        customerService = new CustomerService(cqlSession);
        loadAllCustomers();
    }

    private void loadAllCustomers() {
        List<Customer> products = customerService.getAll();
        String[] columnNames = {"Customer ID", "Name", "Address", "Phone Number"};
        tableModel = new DefaultTableModel(columnNames, 0);
        tblCustomers.setModel(tableModel);
        tableModel.setRowCount(0);
        for (Customer customer : products) {
            Object[] rowData = {
                customer.customer_id,
                customer.name,
                customer.address,
                customer.phone_number
            };
            tableModel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnaddCustomer = new javax.swing.JButton();
        btndeleteCustomer = new javax.swing.JButton();
        btnupdateCustomer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNameCustomer = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddressCustomer = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtIDCustomer = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        textPhoneCustomer = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnexportJson = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        btnaddCustomer.setText("Thêm khách hàng");
        btnaddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddCustomerActionPerformed(evt);
            }
        });

        btndeleteCustomer.setText("Xóa khách hàng ");
        btndeleteCustomer.setToolTipText("");
        btndeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteCustomerActionPerformed(evt);
            }
        });

        btnupdateCustomer.setText("Cập nhật ");
        btnupdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateCustomerActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txtNameCustomer);

        jLabel1.setText("Tên khách hàng ");

        jScrollPane3.setViewportView(txtAddressCustomer);

        jLabel2.setText("Địa chỉ ");

        jScrollPane4.setViewportView(txtIDCustomer);

        jScrollPane5.setViewportView(textPhoneCustomer);

        jLabel3.setText("Mã khách hàng");

        jLabel4.setText("Số điện thoại ");

        btnexportJson.setText("Xuất dữ liệu ");
        btnexportJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportJsonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("KHÁCH HÀNG ");

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomersMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblCustomers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(284, 284, 284))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnaddCustomer)
                        .addGap(45, 45, 45)
                        .addComponent(btndeleteCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnupdateCustomer)
                        .addGap(61, 61, 61)
                        .addComponent(btnexportJson))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane6))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddCustomer)
                    .addComponent(btndeleteCustomer)
                    .addComponent(btnupdateCustomer)
                    .addComponent(btnexportJson))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteCustomerActionPerformed
        // Lấy chỉ số của hàng đã chọn
        int selectedRow = tblCustomers.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy ID của khách hàng từ hàng đã chọn
            String customerID = tblCustomers.getValueAt(selectedRow, 0).toString();
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa khách hàng này không ?", "Xác nhận xóa khách hàng", javax.swing.JOptionPane.YES_NO_OPTION);
            // Xóa khách hàng

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                customerService.deleteCustomer(customerID);
                // Tải lại danh sách khách hàng
                loadAllCustomers();
            }
        } else {
            // Hiển thị thông báo nếu không có hàng nào được chọn
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một khách hàng để xóa.");
        }
    }//GEN-LAST:event_btndeleteCustomerActionPerformed

    private void btnaddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddCustomerActionPerformed
        // TODO add your handling code here:
        String customerID = txtIDCustomer.getText();
        String name = txtNameCustomer.getText();
        String address = txtAddressCustomer.getText();
        String phone_number = textPhoneCustomer.getText();
        Customer customer = new Customer(customerID, name, address, phone_number);
        customerService.addCustomer(customer);
        loadAllCustomers();
    }//GEN-LAST:event_btnaddCustomerActionPerformed

    private void btnupdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateCustomerActionPerformed
        // Kiểm tra xem người dùng đã chọn hàng nào trong bảng chưa
        int selectedRow = tblCustomers.getSelectedRow();
        if (selectedRow != -1) { // Nếu có hàng được chọn
            // Lấy thông tin khách hàng từ hàng đã chọn
            String customerID = tblCustomers.getValueAt(selectedRow, 0).toString();
            String name = txtNameCustomer.getText();
            String address = txtAddressCustomer.getText();
            String phone_number = textPhoneCustomer.getText();

            // Tạo đối tượng Customer mới với thông tin đã chỉnh sửa
            Customer customer = new Customer(customerID, name, address, phone_number);

            // Gọi phương thức cập nhật khách hàng từ CustomerService
            customerService.updateCustomer(customer);

            // Tải lại danh sách khách hàng
            loadAllCustomers();
        } else {
            // Nếu không có hàng nào được chọn, hiển thị thông báo
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn một khách hàng để sửa.");
        }
    }//GEN-LAST:event_btnupdateCustomerActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        int selectedRow = tblCustomer.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy thông tin khách hàng đã chọn
            txtIDCustomer.setText(tblCustomer.getValueAt(selectedRow, 0).toString());
            txtNameCustomer.setText(tblCustomer.getValueAt(selectedRow, 1).toString());
            txtAddressCustomer.setText(tblCustomer.getValueAt(selectedRow, 2).toString());
            textPhoneCustomer.setText(tblCustomer.getValueAt(selectedRow, 3).toString());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void btnexportJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportJsonActionPerformed
        // Tạo một JFileChooser để người dùng chọn đường dẫn lưu file
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Lưu file JSON");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JSON Files", "json");
        fileChooser.setFileFilter(filter);

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();

            // Lấy danh sách khách hàng từ dịch vụ
            List<Customer> customers = customerService.getAll();

            // Chuyển đổi danh sách khách hàng thành JSON
            Gson gson = new Gson();
            String json = gson.toJson(customers);

            // Ghi dữ liệu vào file
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))) {
                writer.write(json);
                JOptionPane.showMessageDialog(this, "Dữ liệu đã được xuất ra file JSON thành công!");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi lưu file: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnexportJsonActionPerformed

    private void tblCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomersMouseClicked
        int selectedRow = tblCustomers.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy thông tin khách hàng đã chọn
            txtIDCustomer.setText(tblCustomers.getValueAt(selectedRow, 0).toString());
            txtNameCustomer.setText(tblCustomers.getValueAt(selectedRow, 1).toString());
            txtAddressCustomer.setText(tblCustomers.getValueAt(selectedRow, 2).toString());
            textPhoneCustomer.setText(tblCustomers.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_tblCustomersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddCustomer;
    private javax.swing.JButton btndeleteCustomer;
    private javax.swing.JButton btnexportJson;
    private javax.swing.JButton btnupdateCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTextPane textPhoneCustomer;
    private javax.swing.JTextPane txtAddressCustomer;
    private javax.swing.JTextPane txtIDCustomer;
    private javax.swing.JTextPane txtNameCustomer;
    // End of variables declaration//GEN-END:variables
}
