/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import static Database.ConnectCassandra.createSession;
import Database.Service.WarrantyPolicyService;
import com.datastax.oss.driver.api.core.CqlSession;
import Model.WarrantyPolicy;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nganh
 */
public class pnlWarrantyPolicy extends javax.swing.JFrame {

    /**
     * Creates new form pnlWarrantyPolicy
     */
    private WarrantyPolicyService warrantyPolicyService;
    CqlSession cqlSession = createSession();

    public pnlWarrantyPolicy() {
        initComponents();
        warrantyPolicyService = new WarrantyPolicyService(cqlSession);
        loadWarrantyPolicies();
        loadProductTypesIntoComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaCS = new javax.swing.JTextField();
        CbbLoaiSP = new javax.swing.JComboBox<>();
        txtTGBH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDK = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableCSBH = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ CHÍNH SÁCH BẢO HÀNH");

        jLabel2.setText("Mã chính sách:");

        jLabel3.setText("Loại sản phẩm:");

        txtMaCS.setName("txtMa"); // NOI18N

        CbbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbbLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbLoaiSPActionPerformed(evt);
            }
        });

        txtTGBH.setName("txtTime"); // NOI18N

        jLabel4.setText("Thời hạn bảo hành:");

        jLabel5.setText("Điều kiện:");

        txtDK.setColumns(20);
        txtDK.setRows(5);
        txtDK.setName("txtDK"); // NOI18N
        jScrollPane1.setViewportView(txtDK);

        btnThem.setText("Thêm Chính sách");
        btnThem.setName("btnThem"); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa Chính Sách");
        btnXoa.setName("btnXoa"); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Cập nhật chính sách ");
        btnSua.setName("btnSua"); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        TableCSBH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableCSBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCSBHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableCSBH);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(91, 91, 91)
                        .addComponent(btnXoa)
                        .addGap(70, 70, 70)
                        .addComponent(btnSua))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)
                                .addComponent(txtMaCS))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CbbLoaiSP, 0, 410, Short.MAX_VALUE)
                                    .addComponent(txtTGBH)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(CbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTGBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnSua)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(55, 55, 55)
                        .addComponent(btnThem)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        addWarrantyPolicy();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        updateWarrantyPolicy();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        deleteWarrantyPolicy();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void TableCSBHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCSBHMouseClicked
        tableRowClicked(evt);
    }//GEN-LAST:event_TableCSBHMouseClicked

    private void CbbLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbLoaiSPActionPerformed
        filterTableByProductType();
    }//GEN-LAST:event_CbbLoaiSPActionPerformed

    private void loadProductTypesIntoComboBox() {
        List<WarrantyPolicy> policies = warrantyPolicyService.getAllWarrantyPolicies();
        CbbLoaiSP.removeAllItems();
        CbbLoaiSP.addItem("Tất cả");
        Set<String> productTypes = new HashSet<>();
        for (WarrantyPolicy policy : policies) {
            productTypes.add(policy.getProductType());
        }
        for (String type : productTypes) {
            CbbLoaiSP.addItem(type);
        }
    }

    public void loadWarrantyPolicies() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã Chính Sách");
        model.addColumn("Loại Sản Phẩm");
        model.addColumn("Mô Tả Chính Sách");
        model.addColumn("Thời Gian Bảo Hành (năm)");
        model.addColumn("Điều Kiện");

        List<WarrantyPolicy> policies = warrantyPolicyService.getAllWarrantyPolicies();

        for (WarrantyPolicy policy : policies) {
            model.addRow(new Object[]{
                policy.getPolicyId(),
                policy.getProductType(),
                policy.getPolicyDescription(),
                policy.getWarrantyDuration(),
                policy.getConditions()
            });
        }

        TableCSBH.setModel(model);
    }

    private void filterTableByProductType() {
        String selectedProductType = (String) CbbLoaiSP.getSelectedItem();
        if (selectedProductType == null) {
            return;
        }
        List<WarrantyPolicy> allPolicies = warrantyPolicyService.getAllWarrantyPolicies();
        DefaultTableModel model = (DefaultTableModel) TableCSBH.getModel();
        model.setRowCount(0);

        if (selectedProductType.equals("Tất cả")) {
            for (WarrantyPolicy policy : allPolicies) {
                model.addRow(new Object[]{
                    policy.getPolicyId(),
                    policy.getProductType(),
                    policy.getPolicyDescription(),
                    policy.getWarrantyDuration(),
                    policy.getConditions()
                });
            }
        } else {
            for (WarrantyPolicy policy : allPolicies) {
                if (policy.getProductType().equals(selectedProductType)) {
                    model.addRow(new Object[]{
                        policy.getPolicyId(),
                        policy.getProductType(),
                        policy.getPolicyDescription(),
                        policy.getWarrantyDuration(),
                        policy.getConditions()
                    });
                }
            }
        }
    }

    private void tableRowClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = TableCSBH.getSelectedRow();

        if (selectedRow != -1) {
            String policyId = TableCSBH.getValueAt(selectedRow, 0).toString();
            String productType = TableCSBH.getValueAt(selectedRow, 1).toString();
            String policyDescription = TableCSBH.getValueAt(selectedRow, 2).toString();
            int warrantyDuration = Integer.parseInt(TableCSBH.getValueAt(selectedRow, 3).toString());
            String conditions = TableCSBH.getValueAt(selectedRow, 4).toString();

            txtMaCS.setText(policyId);
            CbbLoaiSP.setSelectedItem(productType);
            txtDK.setText(conditions);
            txtTGBH.setText(String.valueOf(warrantyDuration));
        }
    }

    private void addWarrantyPolicy() {
        try {
            String policyId = txtMaCS.getText();
            String productType = (String) CbbLoaiSP.getSelectedItem();
            String description = txtDK.getText();
            int duration = Integer.parseInt(txtTGBH.getText());

            WarrantyPolicy newPolicy = new WarrantyPolicy(policyId, productType, description, duration, "Các điều kiện áp dụng");
            warrantyPolicyService.addWarrantyPolicy(newPolicy);

            loadWarrantyPolicies();
            clearForm();
            JOptionPane.showMessageDialog(this, "Thêm chính sách thành công!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm chính sách: " + ex.getMessage());
        }
    }

    private void updateWarrantyPolicy() {
        try {
            String policyId = txtMaCS.getText();
            String productType = (String) CbbLoaiSP.getSelectedItem();
            String description = txtDK.getText();
            int duration = Integer.parseInt(txtTGBH.getText());

            WarrantyPolicy updatedPolicy = new WarrantyPolicy(policyId, productType, description, duration, "Các điều kiện áp dụng");
            warrantyPolicyService.updateWarrantyPolicy(updatedPolicy);

            loadWarrantyPolicies();
            clearForm();
            JOptionPane.showMessageDialog(this, "Cập nhật chính sách thành công!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật chính sách: " + ex.getMessage());
        }
    }

    private void deleteWarrantyPolicy() {
        try {
            String policyId = txtMaCS.getText();
            warrantyPolicyService.deleteWarrantyPolicy(policyId);
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa yêu cầu này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                loadWarrantyPolicies();
                clearForm();
                JOptionPane.showMessageDialog(this, "Xóa chính sách thành công!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa chính sách: " + ex.getMessage());
        }
    }

    private void clearForm() {
        txtMaCS.setText("");
        txtTGBH.setText("");
        txtDK.setText("");
        CbbLoaiSP.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pnlWarrantyPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pnlWarrantyPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pnlWarrantyPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pnlWarrantyPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pnlWarrantyPolicy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbLoaiSP;
    private javax.swing.JTable TableCSBH;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDK;
    private javax.swing.JTextField txtMaCS;
    private javax.swing.JTextField txtTGBH;
    // End of variables declaration//GEN-END:variables
}
