/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import static Database.ConnectCassandra.createSession;
import Database.Service.CustomerService;
import Database.Service.WarrantyClaimService;
import Model.Customer;
import Model.WarrantyClaim;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import com.datastax.oss.driver.api.core.CqlSession;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.time.format.DateTimeParseException;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nganh
 */
public class pnlWarrantyClaim extends javax.swing.JPanel {

    /**
     * Creates new form PnlWarrantyClaimm
     */
    private WarrantyClaimService warrantyClaimService;
    private CustomerService customerService;
    CqlSession cqlSession = createSession();

    public pnlWarrantyClaim() {
        initComponents();
        warrantyClaimService = new WarrantyClaimService(cqlSession);
        customerService = new CustomerService(cqlSession);
        loadAllCustomers();
        loadAllClaims();
        loadStatusIntoComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        CbbStatus = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtMaBH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnExitFilter = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableKH = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDSBH = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNgay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnPDF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(740, 620));

        jLabel5.setText("Mô tả vấn đề:");

        CbbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbStatusActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Bảng Khách Hàng");

        jLabel6.setText("Trạng thái:");

        btnExitFilter.setText("Hủy Lọc");
        btnExitFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitFilterActionPerformed(evt);
            }
        });

        TableKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableKHMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableKH);

        TableDSBH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableDSBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDSBHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableDSBH);

        btnSua.setText("Cập nhật yêu cầu");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã khách hàng:");

        btnXoa.setText("Xóa yêu cầu");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã sản phẩm:");

        btnThem.setText("Thêm yêu cầu");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel4.setText("Ngày yêu cầu:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách bảo hành");

        jLabel7.setText("Mã bảo hành:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Bảng Yêu Cầu Bảo Hành ");

        btnPDF.setText("Xuất File PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua)
                                .addGap(32, 32, 32)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExitFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaBH)
                                    .addComponent(jScrollPane1)
                                    .addComponent(CbbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNgay)
                                    .addComponent(txtMaKH)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMaBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnSua)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExitFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPDF))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CbbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbStatusActionPerformed
        filterTable();
    }//GEN-LAST:event_CbbStatusActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        deleteClaim();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        updateClaim();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        addClaim();
    }//GEN-LAST:event_btnThemActionPerformed

    private void TableDSBHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDSBHMouseClicked
        tableRowClicked(evt);
    }//GEN-LAST:event_TableDSBHMouseClicked

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            if (!filePath.endsWith(".pdf")) {
                filePath += ".pdf";
            }
            try {
                exportTableToPDF(TableDSBH, filePath);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(pnlWarrantyPolicy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnPDFActionPerformed

    private void TableKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableKHMouseClicked
        tableKHRowClicked(evt);
        filterTable();
    }//GEN-LAST:event_TableKHMouseClicked

    private void btnExitFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitFilterActionPerformed
        clearForm();
        resetFilter();
        TableKH.clearSelection();
    }//GEN-LAST:event_btnExitFilterActionPerformed

    private void addClaim() {
        try {
            String claimId = txtMaBH.getText();
            String customerId = txtMaKH.getText();
            String productId = txtMaSP.getText();
            LocalDate claimDate = LocalDate.now();
            String issueDescription = txtMoTa.getText();
            String claimStatus = (String) CbbStatus.getSelectedItem();

            WarrantyClaim newClaim = new WarrantyClaim(claimId, customerId, productId, claimDate, issueDescription, claimStatus);
            warrantyClaimService.submitWarrantyClaim(newClaim);

            loadAllClaims();
            clearForm();
            JOptionPane.showMessageDialog(this, "Yêu cầu bảo hành đã được nộp thành công!");
        } catch (DateTimeParseException dtpe) {
            JOptionPane.showMessageDialog(this, "Lỗi phân tích ngày: " + dtpe.getMessage());
            dtpe.printStackTrace();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi nộp yêu cầu bảo hành: " + ex.getMessage());
        }
    }

    private void updateClaim() {
        try {
            String claimId = txtMaBH.getText();
            String customerId = txtMaKH.getText();
            String productId = txtMaSP.getText();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("uuuu-MM-dd").withLocale(Locale.ENGLISH);
            LocalDate claimDate = LocalDate.parse(txtNgay.getText().trim(), formatter);
            String issueDescription = txtMoTa.getText();
            String claimStatus = (String) CbbStatus.getSelectedItem();

            WarrantyClaim updatedClaim = new WarrantyClaim(claimId, customerId, productId, claimDate, issueDescription, claimStatus);
            warrantyClaimService.updateWarrantyClaim(updatedClaim);

            loadAllClaims();
            clearForm();
            JOptionPane.showMessageDialog(this, "Cập nhật yêu cầu bảo hành thành công!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật yêu cầu bảo hành: " + ex.getMessage());
        }
    }

    private void deleteClaim() {
        try {
            String claimId = txtMaBH.getText();

            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa yêu cầu này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                warrantyClaimService.deleteWarrantyClaim(claimId);
                loadAllClaims();
                clearForm();
                JOptionPane.showMessageDialog(this, "Yêu cầu bảo hành đã được xóa thành công!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa yêu cầu bảo hành: " + ex.getMessage());
        }
    }

    private void loadStatusIntoComboBox() {
        List<WarrantyClaim> sta = warrantyClaimService.getAllWarrantyClaims();
        CbbStatus.removeAllItems();
        CbbStatus.addItem("Tất cả");

        Set<String> claimStatusSet = new HashSet<>();
        for (WarrantyClaim claim : sta) {
            claimStatusSet.add(claim.getClaimStatus());
        }

        for (String status : claimStatusSet) {
            CbbStatus.addItem(status);
        }
    }

    private void filterTable() {
        int selectedRow = TableKH.getSelectedRow();
        String selectedCustomerId = null;
        if (selectedRow != -1) {
            selectedCustomerId = (String) TableKH.getValueAt(selectedRow, 0);
        }
        String selectedStatus = (String) CbbStatus.getSelectedItem();
        if (selectedStatus == null) {
            return;
        }

        List<WarrantyClaim> allClaims = warrantyClaimService.getAllWarrantyClaims();
        DefaultTableModel model = (DefaultTableModel) TableDSBH.getModel();
        model.setRowCount(0);
        for (WarrantyClaim claim : allClaims) {
            if (selectedCustomerId == null || claim.getCustomerId().equals(selectedCustomerId)) {
                if (selectedStatus.equals("Tất cả")) {
                    model.addRow(new Object[]{
                        claim.getClaimId(),
                        claim.getClaimDate(),
                        claim.getClaimStatus(),
                        claim.getCustomerId(),
                        claim.getIssueDescription(),
                        claim.getProductId()
                    });
                } else if (claim.getClaimStatus().equals(selectedStatus)) {
                    model.addRow(new Object[]{
                        claim.getClaimId(),
                        claim.getClaimDate(),
                        claim.getClaimStatus(),
                        claim.getCustomerId(),
                        claim.getIssueDescription(),
                        claim.getProductId()
                    });
                }
            }
        }
    }

    private void loadAllCustomers() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã Khách Hàng");
        model.addColumn("Số Điện Thoại");
        List<Customer> customer = customerService.getAll();
        for (Customer customers : customer) {
            model.addRow(new Object[]{
                customers.getCustomerId(),
                customers.getPhoneNumber()
            });
        }
        TableKH.setModel(model);
    }

    public void loadAllClaims() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã Bảo Hành");
        model.addColumn("Ngày Yêu Cầu");
        model.addColumn("Trạng Thái");
        model.addColumn("Mã Khách Hàng");
        model.addColumn("Mô Tả Vấn Đề");
        model.addColumn("Mã Sản Phẩm");

        List<WarrantyClaim> claims = warrantyClaimService.getAllWarrantyClaims();

        for (WarrantyClaim claim : claims) {
            model.addRow(new Object[]{
                claim.getClaimId(),
                claim.getProductId(),
                claim.getClaimDate(),
                claim.getClaimStatus(),
                claim.getCustomerId(),
                claim.getIssueDescription()
            });
        }

        TableDSBH.setModel(model);
    }

    private void clearForm() {
        txtMaBH.setText("");
        txtMaKH.setText("");
        txtMaSP.setText("");
        txtNgay.setText("");
        txtMoTa.setText("");
        CbbStatus.setSelectedIndex(0);
    }

    private void resetFilter() {
        List<WarrantyClaim> allClaims = warrantyClaimService.getAllWarrantyClaims();
        DefaultTableModel model = (DefaultTableModel) TableDSBH.getModel();
        model.setRowCount(0); 

        for (WarrantyClaim claim : allClaims) {
            model.addRow(new Object[]{
                claim.getClaimId(),
                claim.getClaimDate(),
                claim.getClaimStatus(),
                claim.getCustomerId(),
                claim.getIssueDescription(),
                claim.getProductId()
            });
        }
    }

    private void tableRowClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = TableDSBH.getSelectedRow();

        if (selectedRow != -1) {
            String claimId = TableDSBH.getValueAt(selectedRow, 0).toString();
            String claimDate = TableDSBH.getValueAt(selectedRow, 1).toString();
            String claimStatus = TableDSBH.getValueAt(selectedRow, 2).toString();
            String customerId = TableDSBH.getValueAt(selectedRow, 3).toString();
            String issueDescription = TableDSBH.getValueAt(selectedRow, 4).toString();
            String productId = TableDSBH.getValueAt(selectedRow, 5).toString();

            txtMaBH.setText(claimId);
            txtMaKH.setText(customerId);
            txtMaSP.setText(productId);
            txtNgay.setText(claimDate);
            CbbStatus.setSelectedItem(claimStatus);
            txtMoTa.setText(issueDescription);
        }
    }

    private void tableKHRowClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = TableKH.getSelectedRow();

        if (selectedRow != -1) {
            String customerId = TableKH.getValueAt(selectedRow, 0).toString();
            txtMaKH.setText(customerId);
        }   
    }

    public static void exportTableToPDF(JTable table, String filePath) throws FileNotFoundException {
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();
            BaseFont baseFont = BaseFont.createFont("c:/windows/fonts/arial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            Font font = new Font(baseFont, 12, Font.NORMAL);
            PdfPTable pdfTable = new PdfPTable(table.getColumnCount());
            TableModel model = table.getModel();
            for (int col = 0; col < model.getColumnCount(); col++) {
                pdfTable.addCell(new PdfPCell(new Phrase(model.getColumnName(col), font)));
            }
            for (int row = 0; row < model.getRowCount(); row++) {
                for (int col = 0; col < model.getColumnCount(); col++) {
                    Object value = model.getValueAt(row, col);
                    if (value != null) {
                        pdfTable.addCell(new PdfPCell(new Phrase(value.toString(), font)));
                    } else {
                        pdfTable.addCell(new PdfPCell(new Phrase("", font)));
                    }
                }
            }
            document.add(pdfTable);
            JOptionPane.showMessageDialog(null, "Dữ liệu đã được xuất ra file PDF thành công!");
        } catch (DocumentException | FileNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi xuất dữ liệu ra PDF: " + e.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khác: " + e.getMessage());
        } finally {
            if (document.isOpen()) {
                document.close();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbStatus;
    private javax.swing.JTable TableDSBH;
    private javax.swing.JTable TableKH;
    private javax.swing.JButton btnExitFilter;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtMaBH;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtNgay;
    // End of variables declaration//GEN-END:variables
}
